name: CI
on: push
jobs:
  build:
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test:ci
      - name: Run build
        run: npm run build
