name: CI
on: push
jobs:
  build:

    timeout-minutes: 5
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '18.15.x'
      - name: Install modules
        run: npm install
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test:ci
      - name: Run build
        run: npm run build
